
<div id="middleone">
	<div id="admin_left">
	<ul>
        <li><a href="admin_panel_dash.php">Dashboard</a></li>
		<li><a href="admin_panel_createcourse.php">Create Courses</a></li>
        <li><a href="admin_panel_createexam.php">Create Exam</a></li>
		<li><a href="admin_panel_create_question.php">Set Questions</a></li>
        <li><a href="admin_panel_reports2.php">Exam Reports</a></li>
        <li><a href="admin_panel_appresp.php">Application Response</a></li>
        <li><a href="admin_panel_enqresp.php">Enquiry Response</a></li>
        <li><a href="admin_panel_feedresp.php">Feedback Response</a></li>
    	<li><a href="">Logout</a></li>
    </ul>
</div>

<div id="dynamic">