
	<div id="footermain">
    	<div id="first">
			<div id="about">
        			About Us<a href="aboutus.php"> <br><br> our website provides you the best results...</a></div>
       		 <div id="links">Links
        			<br><ul><li><a href="www.gate.iitk.ac.in">GATE Website</a></li>
            		<li><a href="form_login.php">Login Site</a></li>
                    <li><a href="downloads.php">Download Papers</a></li>
                	 </ul>
        	</div>
        	<div id="enquiry">Enquiry
        			<br><ul><li><a href="help.php">Help and FAQs</a></li>
            		<li><a href="form_enq.php">Enquiry Form</a></li>
                    <li><a href="form_feedback.php"> Give Feedback </a></li>
                 </ul>
       		 </div>
         </div>
     	 <div id="copyright">copyright &copy;</div>
     </div>
   