
<div id="middleone">
	<div id="quicklinks">
    	<h3>QUICK LINKS ...</h3>
	
	<div id="sublinks">
       		<ul> <li><a href="news.php">Notifications</a></li> <br />
                           <li><a href="aboutus.php">About us</a></li><br />
                           <li><a href="courses.php">Courses</a></li><br />
                           <li><a href="references.php">Refrence books</a></li><br />
                           <li><a href="downloads.php">what is Gate??</a></li><br />
                           <li><a href="form_enq.php">Enquiry form</a></li><br />
       		</ul>
   	</div>
	
	
	</div><!--end of quick links-->
<div id="dynamic">