
<div id="userpanel">
    
			
     <ul>
    	<li><a href="user_myprofile.php">MyProfile</a></li>
    	<li><a href="user_editprofile.php">EditProfile</a></li>
    	<li><a href="#">MyTests</a></li>
    	<li><a href="#">MyResults</a></li>
    	<li><a href="#">Help</a></li>
    	<li><a href="user_feedback.php">Feedback</a></li>
    	<li><a href="#">Signout</a></li>
	</ul>
	
	
	</div><!--end of userpanel-->
<div style="clear:both; margin:100px;">
